apiVersion: apps/v1
kind: Deployment
metadata:
  name: AppDeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: my-app
  template:
    metadata:
      labels:
        name: my-app
    spec:
      containers:
      - name: my-app
        image: asia-southeast1-docker.pkg.dev/ahmed-gcp/ahmed-repo/my-img:lastest
        
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: app-cm  